apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: ecommerce-customer
  name: ecommerce-customer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-customer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecommerce-customer
    spec:
      containers:
      - image: ecommerce/customer:0.0.1-SNAPSHOT
        #imagePullPolicy: IfNotPresent
        name: ecommerce-customer-service
        env:
        - name: MONGO_HOST
          value: "ecommerce-mongo.default"
        #envFrom:
         # - configMapRef:
          #    name: ecommerce
#        env:
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
       
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecommerce-customer
  name: ecommerce-customer
  namespace: default
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: ecommerce-customer
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  ECOMMERCE_CUSTOMER_URI: http://ecommerce-customer
kind: ConfigMap
metadata:
  name: ecommerce
  namespace: default