version: '3.9'

services:
  mongo:
    container_name: ecommerce-customer-mongo
    image: mongo:latest
    #restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - ecommerce

  customer:
    container_name: ecommerce-customer
    image: ecommerce/customer:0.0.1-SNAPSHOT
    ports:
      - 8082:8082
    networks:
      - ecommerce
    environment:
      MONGO_HOST: ecommerce-customer-mongo

networks:
  ecommerce:
volumes:
  mongodb_data_container: