apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: ecommerce-mongo
  name: ecommerce-mongo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecommerce-mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: IfNotPresent
        name: ecommerce-mongo-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecommerce-mongo
  name: ecommerce-mongo
  namespace: default
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: ecommerce-mongo
  sessionAffinity: None
#  type: ClusterIP
  type: LoadBalancer
